version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: UCT
  open-pull-requests-limit: 25
  target-branch: main
  reviewers:
  - LNSD
