version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: UTC
    open-pull-requests-limit: 25
    target-branch: main
    reviewers:
      - LNSD

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: UTC
    open-pull-requests-limit: 25
    target-branch: main
    reviewers:
      - LNSD
