= Recording backends

This library uses the `java.utils.ServiceLoader` plugins system to load dynamically from the classpath the video recording backend.

For example to use this library with JUnit5 Test Framework and Monte Scree Recorder video backend:


== Monte screen recorder

.pom.xml
[source,xml,subs="attributes,verbatim"]
----
<dependency>
  <groupId>es.lnsd.videotape</groupId>
  <artifactId>videotape-backend-monte</artifactId>
  <version>{revnumber}</version>
  <scope>test</scope>
</dependency>
----

.build.gradle
[source,groovy,subs="attributes,verbatim"]
----
testRuntimeOnly group: 'es.lnsd.videotape', name: 'videotape-backend-monte', version: '{revnumber}'
----

Recorder based on the link:http://www.randelshofer.ch/monte/[Monte Media Library].
A java library for processing media files based on Java Media Framework (JMF).

== FFMPEG wrapper

.pom.xml
[source,xml,subs="attributes,verbatim"]
----
<dependency>
  <groupId>es.lnsd.videotape</groupId>
  <artifactId>videotape-backend-ffmpeg</artifactId>
  <version>{revnumber}</version>
  <scope>test</scope>
</dependency>
----

.build.gradle
[source,groovy,subs="attributes,verbatim"]
----
testRuntimeOnly group: 'es.lnsd.videotape', name: 'videotape-backend-ffmpeg', version: '{revnumber}'
----

Recorder backend based on a wrapper around FFMPEG command line interface.
This requires the ffmpeg command line executable to be available in the system.

link:https://github.com/kokorin/Jaffree[Jaffree] based command-line interface wrapper.

=== Dependencies

==== Debian

    sudo apt-get update
    sudo apt-get install ffmpeg

==== MacOS

    brew install ffmpeg

==== Windows

* Chocolatey:

    choco install ffmpeg

* Scoop:

    scoop install ffmpeg

==== Manual install

Binaries can be found at FFMPEG's project link:https://ffmpeg.org/download.html[downloads page].

=== Configuration options

|===
|Name |Default value |Description

|_video.ffmpeg.binary_
|`-`
|Command line interface binary path. If not set, the wrapper will use the `ffmpeg` binary available in the `PATH`.

|video.ffmpeg.format
|_OS dependent value (e.g. for MacOS is `avfoundation`)_
|Input format for input device (see link:https://ffmpeg.org/ffmpeg-devices.html#Input-Devices[ffmpeg's `-f` option]).

|video.ffmpeg.display
|_OS dependent value (e.g. for MacOS is `1:`)_
|Input device index (See: link:https://ffmpeg.org/ffmpeg-devices.html#Input-Devices[ffmpeg's `-i` option]).

|video.ffmpeg.pixelFormat
|`yuv420p`
|Specific pixel format (See: link:https://ffmpeg.org/ffmpeg-devices.html#Input-Devices[ffmpeg's `-pixel_format` option]).MacOS specific option.
|===

== VLC

.pom.xml
[source,xml,subs="attributes,verbatim"]
----
<dependency>
  <groupId>es.lnsd.videotape</groupId>
  <artifactId>videotape-backend-vlc</artifactId>
  <version>{revnumber}</version>
  <scope>test</scope>
</dependency>
----

.build.gradle
[source,groovy,subs="attributes,verbatim"]
----
testRuntimeOnly group: 'es.lnsd.videotape', name: 'videotape-backend-vlc', version: '{revnumber}'
----

VLC recorder backend is based on link:https://github.com/caprica/vlcj[vlcj], a Java framework that hides a lot of the complexities of working with LibVLC.

=== Requirements

VLC backend requires VLC 4.0.0+ (LibVLC) to be available in the system.

=== Dependencies

==== Debian

    sudo apt-get update
    sudo apt-get install vlc

==== MacOS

    brew cask install vlc

==== Windows

* Chocolatey:

    choco install vlc

* Scoop:

    scoop install vlc

==== Manual install

Follow instructions at VLC's link:https://www.videolan.org/vlc/index.html[official website].
