name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [ 'assigned', 'opened', 'synchronize', 'reopened' ]
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SCM checkout
        uses: actions/checkout@v3

      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
          check-latest: true

      - name: Run tests
        run: mvn --batch-mode test -Pcov-report

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/target/site/jacoco-aggregate/
          flags: unittests