name: Build and test project modules
on:
  push:
    branches: [ gh-actions ]

jobs:
  build-core:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install ffmpeg vlc
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install ffmpeg vlc
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ffmpeg
            brew cask install vlc
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build with Gradle
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew clean core:build

  build-integrations:
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [ 9, 11, 14 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install ffmpeg vlc
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install ffmpeg vlc
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ffmpeg
            brew cask install vlc
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build with Gradle
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew clean build -x core:test -x docs:build
