name: quality-checks
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
          check-latest: true

      - name: Run linter
        run: mvn --batch-mode --update-snapshots checkstyle:check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: SCM checkout
        uses: actions/checkout@v2

      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
          check-latest: true

      - name: Run unit tests
        run: mvn --batch-mode test -Pcov-report

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/target/site/jacoco-aggregate/
          flags: unittests